version: '3'
services:
  database:
    image: postgres:alpine
    ports: 
      - "5431:5432"
    container_name: postgres-db
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 201984

  myapp:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy