export class PermissionsEnum {
  static STORES_CREATE = "STORES_CREATE";
  static STORES_READ = "STORES_READ";
  static STORES_UPDATE = "STORES_UPDATE";
  static STORES_DELETE = "STORES_DELETE";

  static SUPPLIERS_CREATE = "SUPPLIERS_CREATE";
  static SUPPLIERS_READ = "SUPPLIERS_READ";
  static SUPPLIERS_UPDATE = "SUPPLIERS_UPDATE";
  static SUPPLIERS_DELETE = "SUPPLIERS_DELETE";

  static PRODUCTS_CREATE = "PRODUCTS_CREATE";
  static PRODUCTS_READ = "PRODUCTS_READ";
  static PRODUCTS_UPDATE = "PRODUCTS_UPDATE";
  static PRODUCTS_DELETE = "PRODUCTS_DELETE";

  static INVENTORIES_CREATE = "INVENTORIES_CREATE";
  static INVENTORIES_READ = "INVENTORIES_READ";
  static INVENTORIES_UPDATE = "INVENTORIES_UPDATE";
  static INVENTORIES_DELETE = "INVENTORIES_DELETE";

  static ORDER_ITEMS_CREATE = "ORDER_ITEMS_CREATE";
  static ORDER_ITEMS_READ = "ORDER_ITEMS_READ";
  static ORDER_ITEMS_UPDATE = "ORDER_ITEMS_UPDATE";
  static ORDER_ITEMS_DELETE = "ORDER_ITEMS_DELETE";

  static ORDERS_CREATE = "ORDERS_CREATE";
  static ORDERS_READ = "ORDERS_READ";
  static ORDERS_UPDATE = "ORDERS_UPDATE";
  static ORDERS_DELETE = "ORDERS_DELETE";

  static SALES_CREATE = "SALES_CREATE";
  static SALES_READ = "SALES_READ";
  static SALES_UPDATE = "SALES_UPDATE";
  static SALES_DELETE = "SALES_DELETE";

  static SALE_ITEMS_CREATE = "SALE_ITEMS_CREATE";
  static SALE_ITEMS_READ = "SALE_ITEMS_READ";
  static SALE_ITEMS_UPDATE = "SALE_ITEMS_UPDATE";
  static SALE_ITEMS_DELETE = "SALE_ITEMS_DELETE";

  static PAYMENT_TYPES_CREATE = "PAYMENT_TYPES_CREATE";
  static PAYMENT_TYPES_READ = "PAYMENT_TYPES_READ";
  static PAYMENT_TYPES_UPDATE = "PAYMENT_TYPES_UPDATE";
  static PAYMENT_TYPES_DELETE = "PAYMENT_TYPES_DELETE";

  static EMPLOYEES_CREATE = "EMPLOYEES_CREATE";
  static EMPLOYEES_READ = "EMPLOYEES_READ";
  static EMPLOYEES_UPDATE = "EMPLOYEES_UPDATE";
  static EMPLOYEES_DELETE = "EMPLOYEES_DELETE";

  static USERS_CREATE = "USERS_CREATE";
  static USERS_READ = "USERS_READ";
  static USERS_UPDATE = "USERS_UPDATE";
  static USERS_DELETE = "USERS_DELETE";

  static NONE = "";
}
